# Generated by Django 3.1.1 on 2021-01-09 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('Tenant_Full_Names', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Unspecified')], default='Male', max_length=32)),
                ('National_ID', models.IntegerField(null=True, unique=True)),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True, verbose_name='phone number(work)')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True, verbose_name='phone number(home)')),
                ('occupation_status', models.CharField(choices=[('Self-Employed', 'Self-Employed'), ('Employed', 'Employed'), ('Student', 'Student')], default='Employed', max_length=32)),
                ('at', models.CharField(blank=True, max_length=255)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_tenant', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.customuser')),
                ('image', models.ImageField(blank=True, default='kanjologo.png', upload_to='profile_pics/')),
                ('marital_status', models.CharField(choices=[('SINGLE', 'SINGLE'), ('MARRIED', 'MARRIED')], default='SINGLE', max_length=255)),
            ],
        ),
    ]
