# Generated by Django 3.1.1 on 2021-01-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('bill', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_bills', to=settings.AUTH_USER_MODEL)),
                ('unit_no', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unit_bills', to='unit.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
