# Generated by Django 3.1.1 on 2021-01-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_bill_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='unit_no',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='tenant',
        ),
    ]
