# Generated by Django 3.1.1 on 2021-01-09 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacateTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=10, unique=True)),
                ('unit_type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE'), ('BEDSITTER', 'BEDSITTER'), ('ONE BEDROOM', 'ONE BEDROOM'), ('TWO BEDROOM', 'TWO BEDROOM'), ('THREE BEDROOM', 'THREE BEDROOM'), ('MANSIONETTE', 'MANSIONETTE'), ('SHOP', 'SHOP'), ('STORE', 'STORE')], default='ONE BEDROOM', max_length=255)),
                ('confirm_allocation', models.BooleanField(default=False, verbose_name='Uncheck to vacate tenant')),
                ('select_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeApartment', to='apartment.apartment')),
                ('tenant', models.OneToOneField(max_length=255, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('unit_no', models.CharField(max_length=10, unique=True)),
                ('unit_type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE'), ('BEDSITTER', 'BEDSITTER'), ('ONE BEDROOM', 'ONE BEDROOM'), ('TWO BEDROOM', 'TWO BEDROOM'), ('THREE BEDROOM', 'THREE BEDROOM'), ('MANSIONETTE', 'MANSIONETTE'), ('SHOP', 'SHOP'), ('STORE', 'STORE')], default='ONE BEDROOM', max_length=255)),
                ('rent', models.IntegerField(verbose_name='Monthly Rent(Kshs)')),
                ('confirm_allocation', models.BooleanField(default=False)),
                ('amount', models.IntegerField(null=True)),
                ('deposit', models.IntegerField(default=0)),
                ('rent_paid', models.IntegerField(default=0)),
                ('placement_date', models.DateField(default=django.utils.timezone.now)),
                ('select_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_apartment', to='apartment.apartment')),
                ('tenant', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takenTenants', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocateTenantUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(max_length=10, unique=True)),
                ('unit_type', models.CharField(choices=[('SINGLE', 'SINGLE'), ('DOUBLE', 'DOUBLE'), ('BEDSITTER', 'BEDSITTER'), ('ONE BEDROOM', 'ONE BEDROOM'), ('TWO BEDROOM', 'TWO BEDROOM'), ('THREE BEDROOM', 'THREE BEDROOM'), ('MANSIONETTE', 'MANSIONETTE'), ('SHOP', 'SHOP'), ('STORE', 'STORE')], default='ONE BEDROOM', max_length=255)),
                ('rent', models.IntegerField(null=True, verbose_name='Monthly Rent(Kshs)')),
                ('deposit', models.IntegerField(default=0)),
                ('rent_paid', models.IntegerField(default=0)),
                ('placement_date', models.DateField(default=django.utils.timezone.now)),
                ('confirm_allocation', models.BooleanField(default=True, help_text='Check to confirm')),
                ('select_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takenApartment', to='apartment.apartment')),
                ('tenant', models.ForeignKey(max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
