# Generated by Django 3.1.1 on 2021-01-09 10:00

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('Full_Name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unspecified', 'Unspecified')], default='Male', max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('National_ID', models.IntegerField(verbose_name='ID No.')),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True, verbose_name='phone number')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='KE', unique=True, verbose_name='Emergency Contact')),
                ('post_office_box', models.CharField(blank=True, help_text='e.g P.O BOX 481-800100, Mombasa', max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
